#!/bin/bash
# Setup GitHub remote for facebook_fakebot
# Run this after creating the repo on GitHub

echo "=== GitHub Setup ==="
echo ""
echo "1. Create repo at: https://github.com/new"
echo "   Repository name: facebook_fakebot"
echo "   Description: Facebook clone for bug bounty practice"
echo "   Visibility: Public or Private (pilihan anda)"
echo "   DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. Add SSH key to GitHub:"
echo "   Go to: https://github.com/settings/keys"
echo "   Click 'New SSH key'"
echo "   Title: MyWeb Server"
echo "   Key: $(cat ~/.ssh/id_ed25519.pub)"
echo ""
echo "3. After creating repo and adding SSH key, run:"
echo "   cd /home/tukuk/myweb"
echo "   git remote set-url origin git@github.com:hackbug36-art/facebook_fakebot.git"
echo "   git push -u origin main"
echo ""
echo "=== OR use HTTPS with Personal Access Token ==="
echo ""
echo "1. Create token at: https://github.com/settings/tokens"
echo "   Generate new token (classic)"
echo "   Scopes: repo"
echo ""
echo "2. Run:"
echo "   cd /home/tukuk/myweb"
echo "   git remote set-url origin https://hackbug36:<TOKEN>@github.com/hackbug36-art/facebook_fakebot.git"
echo "   git push -u origin main"
echo ""
echo "=== Current remote ==="
git remote -v
